### ISSUE TITLE
Add French translation

### ISSUE THREAD

**Issue by johnjohndoe** [Umweltzone/roadsigns#14]
It would be nice to have a French translation of the library. :fr: 

The _Translation Editor_ in [_Android Studio_](https://developer.android.com/studio/) let's you easily identify the missing translations as shown in the screenshot.

![Android Studio Translation Editor](https://user-images.githubusercontent.com/144518/95666483-5078fa80-0b5a-11eb-8c80-159c893e6905.png)

# TODOs

- [x] Add new translations in `roadsigns/src/main/res/values-fr/strings.xml`
  - Adding a new language can be done via the _Translation Editor_: the earth icon at top left.
  - Alternatively, you can just copy the English file from `values/strings.xml` to `values-fr/strings.xml` and edit the strings manually.
  - Do not modify, commit files outside of the `-fr` folder.
  - Do not translate strings located in the `app` module.
  - Do not translate strings marked as `translatable="false"`.
  - Please do not commit to the `master` branch. Create a new branch like `french-translation` for the pull request.
  - Check that your translation string is not wrapped in double quotes (`"`) or includes unneeded whitespace.
- [x] Update the `Supported languages` section in the _README.md_. Flags are copied from Twitter emoticons.
- [x] Update the _CHANGELOG.md_.

# Related
- [Localize the UI with Translations Editor](https://developer.android.com/studio/write/translations-editor.html)

---

:left_speech_bubble: If you want to work on this issue please leave a "I like to work on this" comment here.

**Comment by Tititesouris** [comment]
I would like to work on this! :)

**Comment by johnjohndoe** [comment]
Hi @Tititesouris. Nice. You are welcome to do so.

**Comment by Tititesouris** [comment]
Hi @johnjohndoe,
I speak some German, and as it seems that this app is originally written in German I used it as well as the English to help with the translation. It looks to me like the English translation has a lot of small mistakes that make it very awkward to read.

I have a few questions:
The "yellow and green" and "red, yellow and green" -> does it mean that the vehicles should have one of them, or all of them at the same time?
LKWs und Kraftwagen -> LKWs are already Kraftwagen, what is meant by this? How is that different from Fahrzeuge?
Diesel (außer Lieferverkehr) erst ab Euro 5/V frei -> Does that mean that delivery vehicles are allowed no matter their norm, or that they are not allowed at all?

Thank you!

**Comment by johnjohndoe** [comment]
It is indeed confusing. One reason for this is that cities assemble their **own non-standardized** traffic signs in case of the Diesel restrictions. It can be a traffic sign which aims to communicate that vehicles are allowed (e.g. Berlin) or are disallowed (e.g. Stuttgart) to enter the zone.
I am trying to answer your questions:

> The "yellow and green" and "red, yellow and green" -> does it mean that the vehicles should have one of them, or all of them at the same time?

A vehicle can only have one badge at a time.

> LKWs und Kraftwagen -> LKWs are already Kraftwagen, what is meant by this? How is that different from Fahrzeuge?

LKWs is used in German to speak about heavy good vehicles. Another English word would be lorry or truck. I used "cars" for the remaining vehicles. Both cases can be found in Hamburg.

> Diesel (außer Lieferverkehr) erst ab Euro 5/V frei -> Does that mean that delivery vehicles are allowed no matter their norm, or that they are not allowed at all?

My understanding is that delivery vehicles are allowed no matter their norm.

**Comment by Tititesouris** [comment]
So just to be clear:
Fahrzeuge = all motorized vehicles
LKWs = trucks
Kraftwagen (same as PKWs) = cars

**Comment by Tititesouris** [comment]
For the last one. Are vehicles Diesel Euro 5/V allowed (>= 5/V) or not allowed (> 5/V)

**Comment by johnjohndoe** [comment]
``` xml
<string name="diesel_prohibition_free_as_of_euro_5_v_except_delivery_vehicles_stuttgart">
        Strassenschild: Diesel (außer Lieferverkehr) erst ab Euro 5/V frei
</string>
```

Vehicles Diesel Euro 5/V are allowed (>= 5/V).

Regarding "Fahrzeuge", "LKWs", "Kraftwagen" I recommend you to install the demo app and have a look at the traffic signs. This should clarify the individual regulations. I can upload the APK somewhere if you cannot build the app yourself.

**Comment by Tititesouris** [comment]
Here's the PR :) #20
