### ISSUE TITLE
Add Polish translation

### ISSUE THREAD

**Issue by johnjohndoe** [Umweltzone/roadsigns#7]
It would be nice to have a Polish translation of the library. :poland: 

The _Translation Editor_ in [_Android Studio_](https://developer.android.com/studio/) let's you easily identify the missing translations as shown in the screenshot.

![Android Studio Translation Editor](https://user-images.githubusercontent.com/144518/95666483-5078fa80-0b5a-11eb-8c80-159c893e6905.png)

# TODOs

- [x] Add new translations in `roadsigns/src/main/res/values-pl/strings.xml`
  - Adding a new language can be done via the _Translation Editor_: the earth icon at top left.
  - Alternatively, you can just copy the English file from `values/strings.xml` to `values-pl/strings.xml` and edit the strings manually.
  - Do not modify, commit files outside of the `-pl` folder.
  - Do not translate strings located in the `app` module.
  - Do not translate strings marked as `translatable="false"`.
  - Please do not commit to the `master` branch. Create a new branch like `polish-translation` for the pull request.
  - Check that your translation string is not wrapped in double quotes (`"`) or includes unneeded whitespace.
- [x] Update the `Supported languages` section in the _README.md_. Flags are copied from Twitter emoticons.
- [x] Update the _CHANGELOG.md_.

# Related
- [Localize the UI with Translations Editor](https://developer.android.com/studio/write/translations-editor.html)

---

:left_speech_bubble: If you want to work on this issue please leave a "I like to work on this" comment here.
